# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    command: 'buildAndPush'
    #repository: 'mayaaiuga/test-run-image'
    repository: 'theodora755/test-app'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
# - task: DockerCompose@0
#   inputs:
#     containerregistrytype: 'Azure Container Registry'
#     azureSubscription: 'Teodora Nechifor DevOps(2)(0169353e-72e1-499c-8db7-97966d3c1e62)'
#     dockerComposeFile: '**/docker-compose.yml'
#     action: 'Run a Docker Compose command'